### ISSUE TITLE
Query variable builder crashing on Grafana Cloud

### ISSUE THREAD

**Issue by clementduveau** [grafana/google-sheets-datasource#239]
Hello,

trying to use Google Sheets in a query variable on Grafana Cloud, the frontend crashes.

https://github.com/grafana/google-sheets-datasource/assets/17810852/6583bae8-8a92-40b4-abbb-abda40c05157

Error message:

```
Error: Couldn't find a query runner that matches supplied arguments.
    at hu.getRunnerForDatasource (queryRunners.ts:62:11)
    at Lg.onNewRequest (VariableQueryRunner.ts:114:35)
    at L.next (Subscriber.js:96:33)
    at k._next (Subscriber.js:63:26)
    at k.next (Subscriber.js:34:18)
    at Subject.js:41:34
    at c (errorContext.js:19:9)
    at u.next (Subject.js:31:9)
    at Lg.queueRequest (VariableQueryRunner.ts:75:32)
    at actions.ts:50:34
```

Grafana version: Grafana v11.1.0-69051 (9d44c8e8cf)

**Comment by clementduveau** [comment]
Seems related to https://github.com/grafana/grafana/issues/85730

**Comment by zoltanbedi** [comment]
@clementduveau I've just checked on cloud (Grafana v11.1.0-69950) and the console error is not shown anymore. We also have a feature request here https://github.com/grafana/google-sheets-datasource/issues/86 can we close this issue?
